### PR TITLE
Added ReactJS Scaffolding to Master Branch

### LINKED ISSUE #5: [FEATURE] Create Installation/Configuration Instructions For React.js Repo
**Action Required**
Create step-by-step instructions for setting up `develop` React.js repo for local development

### PR DESCRIPTION
**Pull request by onabright**
## Description
I have added ReactJs scaffolding to the master branch to support React development. These changes need to be merged with the develop (default) branch. 

Fixes #5

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MutegekiHenry — APPROVED** [review]
Looks good to go, thanks @onabright

**Comment by pearlonzo** [comment]
i remember talked about avoiding using I and  my

**Comment by MutegekiHenry** [comment]
@pearlonzo @morelmiles @nserekoallan kindly review this PR

**Comment by onabright** [comment]
> i remember talked about avoiding using I and my

@pearlonzo using first-person pronouns like I and Me should NOT be used when writing commits. However, when providing a description for a pull request (PR), for example, or adding comments to a review it is OK. 

In the meantime please review and approve this PR, it is taking too long.

**Review by luigimorel — APPROVED** [review]

**Review by pearlonzo — APPROVED** [review]

**Comment by MutegekiHenry** [comment]
Finally, this PR is merged! guys we should check on the time we take to review PRs

**Pull request merged**
