### PR TITLE
Ft login page

### PR DESCRIPTION
**Pull request by MutegekiHenry**
## Description
Please include a summary of the change and relevant motivation and context. 

- Create a page design for the login page

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes  (#9)

## How Has This Been Tested?
This branch has been run on localhost on the route `/login` and displays the login page

## Screenshots
This is the current state of the login page design
Screenshot from 2020-05-25 11-05-00

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MutegekiHenry** [comment]
@onabright @morelmiles @pearlonzo should I leave the select role part on login or I eliminate it?

**Review by pearlonzo — DISMISSED** [review]

**Comment by pearlonzo** [comment]
i think you should leave it there

**Comment by MutegekiHenry** [comment]
> @onabright @morelmiles @pearlonzo should I leave the select role part on login or I eliminate it?

i have checked the backend endpoint and they don't expect it so I will remove it

**Comment by luigimorel** [comment]
Remove it. Just like you indicated.

**Review by pearlonzo — APPROVED** [review]

**Review by luigimorel — APPROVED** [review]

**Review by pearlonzo — APPROVED** [review]

**Pull request merged**
